# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: zTNP3MF6RZ8RnKRWTnm9q8LXm2+fqEMJ0E4WNQV508NlRwj/J15cSQ45Wbzft9WVba/qx62rBgDoyXXqkiJd7debERTkQkPdEVCvE+22Q3pPuCce4WQ+r1g9LD7h0LAwcVSYXwb8+AjeO9Wp8ujt5NqITL4RXBAULmw/oe8geNWrVIu7rL2MNFTXiYi1eEKukGisdbQfOjeXyvVoaucWPI2P8y9MJvRjswRBwMSh7nEduXknTRigqgYXqtg9vE+926PwHMoxXM4TpKM0Ww/1sCHliSU5xEmSEbXSfuYMysMrofxyh3KtZYU55rSxTGRMn1Ccoda3GkdsbI2QX9f35JHHuZ4+XtlMYtCnESQ/8aGynQFTRUSHyIuu5Ji6r03+0OVrYw0Z6p9sZEHxQXEXyXfW05XbaW+lALm74Q0D/OpEK8lZjsUOMaXgrSu9CDQRr6OA3xJ0LzaqFZfMBdlBi8SuvoKD4jERpaE2vsFKqDbKpTtqXv17bdKHs83exW+bVfha58Ts80jukkDEeWfpY5hokNVXhD5sV0f2PbhBp2yhub9N3E1i6Asn/y+oUoIMA5EZ9s4pzYpLQg37H/5jHDDh3ia4Nc3YoV5oetLxwJLZ5b7d7dd3Q5xChB6H5NyZkeRxYwhsVhmN2JAixvyKWw8vqGr2XfpYR6C7eB6cMQk=
    # SAUCE_TOKENS with -r 59naga/history-json
    - secure: 29U35r7cs8vvHesZWgG8FKhn6H8zX29i9qB/d/EbaPqrlPXz/is/Zqyno8bviplUQGEBYfG98cZqfGMPniEPBL5r+rALeUt6V7c2FnDB+znLRxIPZv7rQOj+45J0i8Ja7Zdokny/Sv/aw8Z6UAc4qs0LcYAwcLMQvUY7xUejr8GQSRs3qzLrRSp41Z51NjUAD3eVIPJpZQagg11FmEJZ8+4FNyP2mADyicN1xyvDGeuSYjBdDm1q0e/H8BogILtzDYUy/6JHvmsfAXrMlLuL41cxiOE8vTcb6+8Z1XGyiKvh9/1nvULGvogPAcqHB6Io0A7wgt+0nokCivnBmtva5Q7FAzrlDYtW1tNChkQTkNJmaSldrYr82QUHLzbon1nNAappVWrD3fIobN+RbcssQc59qxcRCQU1MjW/ObduPtOor+BOisrjAOFq020nyYWX8CMYEUediX/tvdfb2QWTl3UlPkhOWlzYdgvP910AWhsCQYP2EhkJBxSNMgWsUHzBXlHyqcpS1WUsPDOjsGk0PtWzZuNfzZhy23KaIlZMnuQ3GopqIQcWdT71HfzvP105E0JTd1ilXRk1xRAGcHY+JSCs3wN3pzYhAPn15r91PMcI+WFn8yORqoRqzsvU7iLZWnaeNLlAppsKpCY98ADkDY7Vk3z8Ic2nEz0BnSVJbd0=
    - secure: g7fHK1izUsjXDItDkhmgBrPEKyQ8Ot0GLdMO6b8ejQ8xnHlbwwlRZ2jAhENuplWerxm5ZVGITCaNHATo8qNLw5qEV39LwgNLRBtB0YmLOwPGxfXFhCoIWeJIKdXMPyCRk4M9LHDqkyB8Jt921jjhCv3h4hqjcjm9ugvVRyfmBYf093sYA1P9aI57CDQJ+sfCGbHKePT07Mu9Ny5Iidez/z4n+GxQQWWGK4tGLqGIwc8XCfuSrdBWLPB4BnfzJORsKVyhxaRunp5L15GtXAldcUHHPv6CUuqGQIDrIpTkVvnlBS4V9sX+CqpQaWt80jRFQI3PL8RGjvybgUbynMef1sjuh9eaooah+d1SoNaPcW/dr3QWEop4ZnGvvu50arIFHtzghZYhH5BTrccSmlrdN4YrKc3uSPIxoJQJwqW+nlseyshAesHrNr5buP3MIoTRaS5NfKczUpm2mvGAO0m7xNA/oVW+IJ6DEYYfZ2ZR4zUH1xeq10OIGZbvcjPiqwF67ghB63qEwmFxxG1TzIcoHBQTFf2rTdbnskGaCxOJMvkD/FIZbuhddnHn6TJ/XbUARnd+Ng/9O4XyUv9VqF2705JcyBtuvWXD/nCcF1Wk1ivcG23lWgWEjc0gyyuROXjHR1cP2Gd6CmFwL99W+qm3tdJfwrPf2f33ZivpzJnew1c=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: igaXF1x/UaHlz7VNJe5w/rhfkUTs9Sg8MaxmdZzK3GSsJFqE9jzbNM59Jih81bDP5Lad4vDAQ+gKTyqrY/5tkPddr7xf6EqtAsZmNnjm28IWrzeQLhFb3n54gf+vYSzXFoNbFg7ubnbL6Dxf5O7yVH3w6Yge0zE6JxiFoNfP8SXtUWwod9XjoSpKX+dT2uPyjXZnDgZ4K1AzkBUJDySWkgGDuEVfPocy1QevU/2OBo/sklewaoFkQiDLUXSZHeST0r5AcC+iEMxuPk6ahLk0l74PvZDY5EgcWEWfazBvJjALYmC7FnPExnK/wW+UF12sDPGZTKDNSlHaCrQ2m1ittxNHM3Ub5HwhMbl9dU2IDs6V9upfHmojIsGKh52v37jDNimP2eXJbSEdwYEc/wR5d1tS7HUf4GdZjy9q9KNCmu7MXsKiHqe+bkm5gABUA7RJ0ZAytsQGuAF/qaadqaaOi7CCIkallC1ApIR1UcnHm39gRT6yFqwIROZ4wJrdXHYg6rin46bqUVxDRBrHsncaZmmtXMe9gTD4WjtUAarWbBprUMBWRuhmskB3xG4ahzUFlPr0ibjfV1tteTRh9kHnG5FcdDTVOUAWHzG/Z7y2NdurF2sXRASCrKo0hL5YcU3CY2J79ysH60NBSBzFrXHQkvZK8SwVE9Ps1m6IUtsCQsU=
  on:
    tags: true