# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Language options
language: node_js
node_js:
  - '0.10'

# Coveralls.io options
env:
  global:
    secure: zTNP3MF6RZ8RnKRWTnm9q8LXm2+fqEMJ0E4WNQV508NlRwj/J15cSQ45Wbzft9WVba/qx62rBgDoyXXqkiJd7debERTkQkPdEVCvE+22Q3pPuCce4WQ+r1g9LD7h0LAwcVSYXwb8+AjeO9Wp8ujt5NqITL4RXBAULmw/oe8geNWrVIu7rL2MNFTXiYi1eEKukGisdbQfOjeXyvVoaucWPI2P8y9MJvRjswRBwMSh7nEduXknTRigqgYXqtg9vE+926PwHMoxXM4TpKM0Ww/1sCHliSU5xEmSEbXSfuYMysMrofxyh3KtZYU55rSxTGRMn1Ccoda3GkdsbI2QX9f35JHHuZ4+XtlMYtCnESQ/8aGynQFTRUSHyIuu5Ji6r03+0OVrYw0Z6p9sZEHxQXEXyXfW05XbaW+lALm74Q0D/OpEK8lZjsUOMaXgrSu9CDQRr6OA3xJ0LzaqFZfMBdlBi8SuvoKD4jERpaE2vsFKqDbKpTtqXv17bdKHs83exW+bVfha58Ts80jukkDEeWfpY5hokNVXhD5sV0f2PbhBp2yhub9N3E1i6Asn/y+oUoIMA5EZ9s4pzYpLQg37H/5jHDDh3ia4Nc3YoV5oetLxwJLZ5b7d7dd3Q5xChB6H5NyZkeRxYwhsVhmN2JAixvyKWw8vqGr2XfpYR6C7eB6cMQk=

# Npm publish options
deploy:
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: igaXF1x/UaHlz7VNJe5w/rhfkUTs9Sg8MaxmdZzK3GSsJFqE9jzbNM59Jih81bDP5Lad4vDAQ+gKTyqrY/5tkPddr7xf6EqtAsZmNnjm28IWrzeQLhFb3n54gf+vYSzXFoNbFg7ubnbL6Dxf5O7yVH3w6Yge0zE6JxiFoNfP8SXtUWwod9XjoSpKX+dT2uPyjXZnDgZ4K1AzkBUJDySWkgGDuEVfPocy1QevU/2OBo/sklewaoFkQiDLUXSZHeST0r5AcC+iEMxuPk6ahLk0l74PvZDY5EgcWEWfazBvJjALYmC7FnPExnK/wW+UF12sDPGZTKDNSlHaCrQ2m1ittxNHM3Ub5HwhMbl9dU2IDs6V9upfHmojIsGKh52v37jDNimP2eXJbSEdwYEc/wR5d1tS7HUf4GdZjy9q9KNCmu7MXsKiHqe+bkm5gABUA7RJ0ZAytsQGuAF/qaadqaaOi7CCIkallC1ApIR1UcnHm39gRT6yFqwIROZ4wJrdXHYg6rin46bqUVxDRBrHsncaZmmtXMe9gTD4WjtUAarWbBprUMBWRuhmskB3xG4ahzUFlPr0ibjfV1tteTRh9kHnG5FcdDTVOUAWHzG/Z7y2NdurF2sXRASCrKo0hL5YcU3CY2J79ysH60NBSBzFrXHQkvZK8SwVE9Ps1m6IUtsCQsU=
